// import PazurGamePic from '../images/photo/pazur_gra.jpg'
// import PazurPullsPic from '../images/photo/pazur_sciaga.jpg'
// import PazurCapPic from '../images/photo/pazur_czapa.jpg'
// import ChristmasTreePic from '../images/photo/choinka.jpg'
// import McPic from '../images/photo/zlote_luki.jpg'
// import WelcomePic from '../../resources/images/photo/powitanie.jpg'
// import Background from '../../../resources/trash-background.jpg'